name: Publish PHP Library

on:
  push:
    branches: [ "main", "master" ]
  workflow_dispatch:

jobs:
  publish-php:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    
    steps:
    - uses: actions/checkout@v4

    - name: Set up JDK 8
      uses: actions/setup-java@v4
      with:
        java-version: '8'
        distribution: 'temurin'

    - name: Build PHP Library
      run: ./gradlew copyPhpLib

    - name: Deploy to php branch
      uses: JamesIves/github-pages-deploy-action@v4
      with:
        folder: publish/php-lib
        branch: php
        clean: true
